---
title: "TidyTuesday - Dubois Challenge"
author: "Danagul Kaliyeva"
date: "2/18/2021"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```

```{r}
tuesdata <- tidytuesdayR::tt_load(2021, week = 8)

georgia_pop <- tuesdata$georgia_pop #Population change by race in Georgia.
```

```{r}
georgia_pop %>%
  ggplot() +
  geom_line(aes(y = Colored, x = Year, linetype = "COLORED")) +
  geom_line(aes(y = White, x = Year, linetype = "WHITE")) +
  coord_flip() +
  scale_x_continuous(breaks = seq(1790, 1890, 10),
                     expand = expand_scale(c(0, 0)),
                     name = "") +
  scale_y_continuous(breaks = seq(0, 100, 5), 
                     expand = expand_scale(c(0, 0)),
                     trans = "reverse", 
                     name = "PERCENTS") +
  scale_linetype_manual(name = "",
                        breaks = c("COLORED", "WHITE"),
                        values = c("COLORED" = "solid", "WHITE" = "longdash")) +
  labs(title = "COMPARATIVE INCREASE OF WHITE AND COLORED \nPOPULATION OF GEORGIA.") +
  theme_minimal() +
  theme(
    plot.title = element_text(face = "bold", 
                              size = 16,
                              hjust = 0.5,
                              family = "sans"),
    plot.caption = element_text(),
    plot.margin = margin(10, 150, 10, 120),
    plot.background = element_rect(fill = "antiquewhite2"),
    panel.background = element_rect(fill="antiquewhite2"),
    panel.grid.major = element_line(colour = "red", 
                                    size = 0.1),
    panel.grid.minor = element_line(size = 0),
    axis.title.x = element_text(family = "sans",
                                size = 7, 
                                vjust = -4.5),
    legend.text = element_text(family = "sans",
                               size = 7,
                               margin = margin(c(0, 3, 0, 0), unit = "pt")),
    legend.position = "bottom",
    legend.box = "vertical",
    legend.spacing.x = unit(1.0, 'cm'),
    legend.key.width = unit(3.0, "cm"))
```

